include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - third_party/flutter_vision/**
    - third_party/flutter_vision/example/**
    - third_party/flutter_vision/test/**
    - third_party/flutter_vision/.dart_tool/**
    - third_party/flutter_vision/build/**
